agonyz.generate_meme:
  path: /agonyz/generate-meme
  methods: POST
  defaults:
    _controller: Agonyz\ContaoMemeGeneratorBundle\Controller\MemeGeneratorController::generateMeme
    _scope: frontend
    _token_check: true
    _custom_backend_view: false